[workspace]
resolver = "3"
members = [
  "crates/backend",
  "crates/frontend",
  "crates/hypha-runner",
  # "crates/modules" # пока не реализовано
]

[workspace.package]
version = "0.1.0"
edition = "2024"
description = "Hytale launcher oriented on modding."
license = "MIT"

[workspace.dependencies]
hypha-backend = { path = "crates/backend" }

[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = "limited"
lto = "thin"
codegen-units = 1
